[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
seed = "0x1"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[invariant]
runs = 3000
depth = 64
fail_on_revert = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 150
wrap_comments = true
multiline_func_header = "all"


remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
]

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
